#!/bin/sh
# Xcode Cloud runs this right after cloning, before resolving the project.
# The iOS Xcode project is generated by XcodeGen (project.yml is the source of
# truth; the .xcodeproj is not committed), so generate it here or the build
# fails with "Project Nardi.xcodeproj does not exist".
set -e

echo "Installing XcodeGen…"
brew install xcodegen

echo "Generating ios/Nardi.xcodeproj from project.yml…"
cd "$CI_PRIMARY_REPOSITORY_PATH/ios"
xcodegen generate

echo "Generated project:"
ls -d Nardi.xcodeproj
